"use strict";

const fs = require("fs");
const path = require("path");

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function toPosix(p) { return p.replace(/\\/g, '/'); }

async function buildGame({ projectRoot, config, outDir }) {
  const cliRoot = path.resolve(__dirname, "../..");
  const outAbs = path.resolve(projectRoot, outDir || "dist");
  const genDir = ensureDir(path.join(projectRoot, 'generate'));
  const cfgPath = path.join(genDir, 'vite.build.config.mjs');

  // Use static config from package and pass parameters
  const cfg = [
    "// Auto-generated by @vuevn/cli. Do not edit.",
    `import createBuildConfig from ${JSON.stringify(toPosix(path.join(cliRoot, 'vite-build', 'vite.config.js')))};`,
    "",
    `const projectRoot = ${JSON.stringify(toPosix(projectRoot))};`,
    `const cliRoot = ${JSON.stringify(toPosix(cliRoot))};`,
    `const outDir = ${JSON.stringify(outDir || 'dist')};`,
    "",
    "export default createBuildConfig({ projectRoot, cliRoot, outDir });",
    "",
  ].join("\n");
  fs.writeFileSync(cfgPath, cfg, 'utf8');

  // Spawn the project's Vite CLI (no fallback)
  const viteBin = path.join(projectRoot, 'node_modules', '.bin', 'vite');
  if (!fs.existsSync(viteBin)) {
    throw new Error("Vite CLI not found in project. Install it with: npm i -D vite @vitejs/plugin-vue");
  }
  await new Promise((resolve, reject) => {
    const { spawn } = require('child_process');
    const child = spawn(viteBin, ['build', '--config', cfgPath], { stdio: 'inherit', cwd: projectRoot, env: process.env });
    child.on('exit', async (code) => {
      if (code === 0) {
        // Copy assets after successful build
        try {
          const { copyProjectAssets } = require('../utils/copyAssets');
          await copyProjectAssets({
            projectRoot,
            outDir: outAbs,
            verbose: process.env.VUEVN_VERBOSE === 'true'
          });
        } catch (e) {
          console.warn('⚠️  Asset copy failed:', e.message);
        }
        // After Vite completes and assets are copied, print final output filename
        try {
          const pkgPath = path.join(projectRoot, 'package.json');
          const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8')) || {};
          const projectName = pkg.name || 'game';
          const projectVersion = pkg.version || '1.0.0';
          const outputFilename = `${projectName}-${projectVersion}.html`;
          const finalPath = path.join(outAbs, outputFilename);
          if (fs.existsSync(finalPath)) {
            console.log(`✅ Game built as ./dist/${outputFilename}`);
          }
        } catch { }
        resolve();
      } else {
        reject(new Error(`Vite build failed with exit code ${code}`));
      }
    });
    child.on('error', (err) => reject(err));
  });
}

module.exports = { buildGame };
