"use strict";

const fs = require("fs");
const path = require("path");

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function toPosix(p) { return p.replace(/\\/g, '/'); }

async function buildGame({ projectRoot, config, outDir }) {
  const cliRoot = path.resolve(__dirname, "../..");
  const outAbs = path.resolve(projectRoot, outDir || "dist");
  const genDir = ensureDir(path.join(projectRoot, 'generate'));
  const cfgPath = path.join(genDir, 'vite.build.config.mjs');
  
  // Copy index.html to project root temporarily
  const sourceHtml = path.join(cliRoot, 'vite-build', 'index.html');
  const tempHtml = path.join(projectRoot, 'index.html');
  fs.copyFileSync(sourceHtml, tempHtml);

  const cfg = [
    "// Auto-generated by @vuevn/cli. Do not edit.",
    "import vue from '@vitejs/plugin-vue';",
    "import { viteSingleFile } from 'vite-plugin-singlefile';",
    "import tailwindcss from 'tailwindcss';",
    "import autoprefixer from 'autoprefixer';",
    `import { createVueVNAliasPlugin } from ${JSON.stringify(toPosix(path.join(cliRoot, 'src/plugins/vuevn-alias.js')))};`,
    "export default {",
    `  root: ${JSON.stringify(toPosix(projectRoot))},`,
    "  base: './', // Use relative paths for assets",
    "  plugins: [",
    "    vue(),",
    "    viteSingleFile(), // Single-file build like original VueVN",
    `    createVueVNAliasPlugin({ projectRoot: ${JSON.stringify(toPosix(projectRoot))}, cliRoot: ${JSON.stringify(toPosix(cliRoot))} }),`,
    "  ],",
    "  // Traiter le framework comme du source code, pas du code bundlé",
    "  optimizeDeps: {",
    "    exclude: ['@vuevn/cli']",
    "  },",
    "  css: {",
    "    postcss: {",
    "      plugins: [",
    `        tailwindcss({`,
    `          content: [`,
    `            ${JSON.stringify(toPosix(path.join(cliRoot, 'vite-build/**/*.{vue,js,ts,jsx,tsx}')))},`,
    `            ${JSON.stringify(toPosix(path.join(cliRoot, 'engine_src/**/*.{vue,js,ts,jsx,tsx}')))},`,
    `            ${JSON.stringify(toPosix(path.join(projectRoot, 'generate/**/*.{vue,js,ts,jsx,tsx}')))},`,
    `            ${JSON.stringify(toPosix(path.join(projectRoot, '**/*.{vue,js,ts,jsx,tsx}')))},`,
    `          ]`,
    `        }),`,
    "        autoprefixer()",
    "      ],",
    "    },",
    "  },",
    "  build: {",
    `    outDir: ${JSON.stringify(toPosix(outAbs))},`,
    "    emptyOutDir: false,",
    "    rollupOptions: {",
    `      input: ${JSON.stringify(toPosix(tempHtml))},`,
    "    },",
    "  },",
    "  // Support SSR si nécessaire",
    "  ssr: {",
    "    noExternal: ['@vuevn/cli']",
    "  },",
    "};",
    "",
  ].join("\n");
  fs.writeFileSync(cfgPath, cfg, 'utf8');

  // Spawn the project's Vite CLI (no fallback)
  const viteBin = path.join(projectRoot, 'node_modules', '.bin', 'vite');
  if (!fs.existsSync(viteBin)) {
    throw new Error("Vite CLI not found in project. Install it with: npm i -D vite @vitejs/plugin-vue");
  }
  try {
    await new Promise((resolve, reject) => {
      const { spawn } = require('child_process');
      const child = spawn(viteBin, ['build', '--config', cfgPath], { stdio: 'inherit', cwd: projectRoot, env: process.env });
      child.on('exit', async (code) => {
        if (code === 0) {
          // Copy assets after successful build
          try {
            const { copyProjectAssets } = require('../utils/copyAssets');
            await copyProjectAssets({ 
              projectRoot, 
              outDir: outAbs, 
              verbose: process.env.VUEVN_VERBOSE === 'true' 
            });
          } catch (e) {
            console.warn('⚠️  Asset copy failed:', e.message);
          }
          resolve();
        } else {
          reject(new Error(`Vite build failed with exit code ${code}`));
        }
      });
      child.on('error', (err) => reject(err));
    });
  } finally {
    // Clean up temporary HTML file
    if (fs.existsSync(tempHtml)) {
      fs.unlinkSync(tempHtml);
    }
  }
}

module.exports = { buildGame };

