// src/generator/projectActionsAndEvents.js

import { join } from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';

async function writeTextFile(dir, name, content) {
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, name), content, 'utf8');
}

function collectFiles(node, parts = []) {
  let files = [];
  if (node.files) {
    for (const file of node.files) {
      if (file.ext.toLowerCase() === '.ts') {
        files.push([...parts, file.name]);
      }
    }
  }
  if (node.dirs) {
    for (const dirName in node.dirs) {
      files = files.concat(collectFiles(node.dirs[dirName], [...parts, dirName]));
    }
  }
  return files;
}

export async function writeProjectActionsAndEvents(gen) {
  const projectDir = join(gen.generate_dir, 'project');
  const kinds = ['actions', 'events'];
  const result = {
    global: {},
    locations: {}
  };

  // Global
  for (const kind of kinds) {
    const kindNode = gen.last_tree.global?.dirs?.[kind];
    if (kindNode) {
      const files = collectFiles(kindNode);
      result.global[kind] = files.map(fileParts => ({
        key: fileParts.join('.'),
        path: `@global/${kind}/${fileParts.join('/')}`
      }));
    }
  }

  // Locations
  const locationIds = Object.keys(gen.last_tree.locations?.dirs || {}).sort();
  for (const id of locationIds) {
    result.locations[id] = {};
    for (const kind of kinds) {
      const kindNode = gen.last_tree.locations.dirs[id]?.dirs?.[kind];
      if (kindNode) {
        const files = collectFiles(kindNode);
        result.locations[id][kind] = files.map(fileParts => ({
          key: fileParts.join('.'),
          path: `@locations/${id}/${kind}/${fileParts.join('/')}`
        }));
      }
    }
  }

  const imports = [];
  const flatList = [];
  let importCounter = 0;

  const processKind = (kind, items) => {
    if (!items) return;
    for (const item of items) {
        const importAlias = `i${importCounter++}`;
        imports.push(`import ${importAlias} from '${item.path}';`);
        flatList.push(`  "${item.key}": ${importAlias}`);
    }
  };

  processKind('global.actions', result.global.actions);
  processKind('global.events', result.global.events);

  for(const locationId in result.locations) {
    processKind(`locations.${locationId}.actions`, result.locations[locationId].actions);
    processKind(`locations.${locationId}.events`, result.locations[locationId].events);
  }


  const content = `// Generated by projectActionsAndEvents.js
${imports.join('\n')}

export const actions = {
${flatList.join(',\n')}
};

export default actions;
`;

  await writeTextFile(projectDir, 'index.ts', content);
}
