// src/generator/texts.js
import { join } from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import { build } from 'esbuild';
import { glob } from 'fast-glob';

async function writeTextFile(dir, name, content) {
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, name), content, 'utf8');
}

async function parseTypescript(filePath) {
  const result = await build({
    entryPoints: [filePath],
    bundle: true,
    write: false,
    format: 'esm',
  });
  const code = new TextDecoder().decode(result.outputFiles[0].contents);
  // This is a hack to execute the bundled code and get the default export.
  // It's not ideal, but it's the simplest way to get the data from the TS file.
  const dataUri = `data:text/javascript;charset=utf-8,${encodeURIComponent(code)}`;
  const module = await import(dataUri);
  return module.default;
}

function mergeObjects(target, source) {
  for (const key in source) {
    if (source.hasOwnProperty(key)) {
      if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
        if (!target[key]) {
          target[key] = {};
        }
        mergeObjects(target[key], source[key]);
      } else {
        target[key] = source[key];
      }
    }
  }
}

function createLanguageObject(languages, data, lang) {
    const result = {};
    for (const key in data) {
        if (typeof data[key] === 'object' && data[key] !== null && !Array.isArray(data[key])) {
            result[key] = createLanguageObject(languages, data[key], lang);
        } else {
            result[key] = {};
            for (const l of languages) {
                result[key][l] = l === lang ? data[key] : null;
            }
        }
    }
    return result;
}

function combineWith(target, source) {
    for (const key in source) {
        if (source.hasOwnProperty(key)) {
            if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key]) && target[key]) {
                combineWith(target[key], source[key]);
            } else if (target[key] && typeof target[key] === 'object') {
                Object.assign(target[key], source[key]);
            } else {
                target[key] = source[key];
            }
        }
    }
}


export async function writeTexts(gen) {
  const languages = (gen.config.languages || [{code: 'en'}]).map(lang => lang.code);
  const textsDir = join(gen.generate_dir, 'texts');
  const finalObject = {};

  const processPath = async (path, basePath) => {
    const files = await glob('**/*.ts', { cwd: path });
    const langData = {};

    for (const file of files) {
      const lang = file.split('/').pop().replace('.ts', '');
      const filePath = join(path, file);
      const data = await parseTypescript(filePath);
      langData[lang] = data;
    }

    const allKeys = {};
    for (const lang in langData) {
        mergeObjects(allKeys, langData[lang]);
    }

    const perLangObjects = {};
    for(const lang in langData) {
        perLangObjects[lang] = createLanguageObject(languages, langData[lang], lang);
    }

    const combined = {};
    for(const lang of languages) {
        if(perLangObjects[lang]) {
            combineWith(combined, perLangObjects[lang]);
        }
    }

    let current = finalObject;
    for (const part of basePath.split('/')) {
      if (!current[part]) {
        current[part] = {};
      }
      current = current[part];
    }

    combineWith(current, combined);
  };

  const globalTextsPath = join(gen.project_path, 'global', 'texts');
  await processPath(globalTextsPath, 'global');

  const locationIds = Object.keys(gen.last_tree.locations?.dirs || {}).sort();
  for (const id of locationIds) {
    const locationTextsPath = join(gen.project_path, 'locations', id, 'texts');
    await processPath(locationTextsPath, `locations/${id}`);
  }

  const content = `// Generated by texts.js
export const texts = ${JSON.stringify(finalObject, null, 2)};
export default texts;
`;

  await writeTextFile(textsDir, 'index.ts', content);
}
